package com.marketPlace.MarketPlace.entity.Enums;

public enum NotificationType {
    ORDER_CONFIRMED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_UPDATE,
    PAYMENT_FAILED,
    NEW_MESSAGE,
    CART_UPDATED,
    PRODUCT_REQUEST_SUBMITTED,
    PRODUCT_REQUEST_VIEWED,
    PRODUCT_REQUEST_APPROVED,
    PRODUCT_REQUEST_REJECTED,
    NEW_PRODUCT_ADDED
}